(function(){"use strict";
 var profileId=typeof location!=="undefined"?(new URLSearchParams(location.search).get("id")||""):"",profile=null,loaded={};
 var config={company:{title:"Podjetje",cost:"10 kreditov ob prvem odpiranju; nato se uporabi svež predpomnilnik."},ownership:{title:"Vodstvo in lastništvo",cost:"Lastniki 10 + deleži 10 kreditov. UBO (25) in zgodovina (25) samo na izrecen klik."},financials:{title:"Finance",cost:"10 kreditov ob prvem odpiranju; podatki se hranijo 7 dni."},documents:{title:"Dokumenti in zgodovina",cost:"Seznam 10 kreditov. Posamezen dokument se prenese samo na izrecen klik (10 kreditov)."},insolvency:{title:"Insolvenca",cost:"10 kreditov ob prvem odpiranju; rezultat se hrani 12 ur."},monitoring:{title:"Spremljanje",cost:"Tedensko: 25 ob vključitvi + 25 mesečno. Dnevno: 50 ob vključitvi + 50 mesečno."},overview:{title:"Rezultat zadnje preverbe",cost:""}};
 function el(id){return document.getElementById(id)} function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]})}
 async function token(){var r=await supabaseKlient.auth.getSession();if(!r.data.session)throw new Error("Za nadaljevanje se prijavite.");return r.data.session.access_token}
 function mergedUrl(url){if(url.indexOf("/api/boniteta-profili")===0)return "/api/boniteta-pro?route=profiles"+(url.includes("?")?"&"+url.split("?")[1]:"");if(url.indexOf("/api/openregister-pro")===0)return "/api/boniteta-pro?route=openregister"+(url.includes("?")?"&"+url.split("?")[1]:"");return url}
 async function api(url,opt){var o=Object.assign({},opt||{}),t=await token();o.headers=Object.assign({Authorization:"Bearer "+t,"Content-Type":"application/json"},o.headers||{});if(!o.signal&&typeof AbortSignal!=="undefined"&&AbortSignal.timeout)o.signal=AbortSignal.timeout(45000);var r;try{r=await fetch(mergedUrl(url),o)}catch(e){if(e&&(e.name==="TimeoutError"||e.name==="AbortError"))throw new Error("Pridobivanje podatkov je trajalo predolgo. Poskusite ponovno.");throw e}var d=await r.json().catch(function(){return{}});if(!r.ok||d.ok===false){var x=new Error(d.napaka||"Podatkov ni bilo mogoče pridobiti.");x.code=d.code;throw x}return d}
 function fail(e){el("bp-profile-error").textContent=e.message||String(e);el("bp-profile-error").hidden=false;el("bp-section-state").hidden=true}
 function present(v){return !(v==null||v===""||(Array.isArray(v)&&!v.length))}
 function first(){for(var i=0;i<arguments.length;i++)if(present(arguments[i]))return arguments[i];return ""}
 function slovenskiStatus(v){var s=String(v||"").toLowerCase(),m={active:"Aktivno",inactive:"Neaktivno",clear:"Ni najdene objave",possible_match:"Možen zadetek",unavailable:"Ni dosegljivo",verified_api:"Potrjeno prek API-ja",captured:"Dokazilo zajeto",legal_person:"Pravna oseba",natural_person:"Fizična oseba",processing:"V obdelavi",pending:"V obdelavi",completed:"Pripravljeno",ready:"Pripravljeno",done:"Pripravljeno",failed:"Neuspešno",error:"Napaka"};return m[s]||v||"Ni podatka"}
 function datum(v){if(!present(v))return "";var d=new Date(v);return isNaN(d.getTime())?String(v):d.toLocaleString("sl-SI")}
 function denar(amount,currency){if(!present(amount))return "";var n=Number(amount);return isFinite(n)?new Intl.NumberFormat("sl-SI",{style:"currency",currency:currency||"EUR",maximumFractionDigits:2}).format(n):String(amount)+(currency?" "+currency:"")}
 function vrstica(label,value,options){if(!present(value))return "";var o=options||{},display=o.status?slovenskiStatus(value):o.date?datum(value):String(value);return '<div class="bp-info-row"><dt>'+esc(label)+'</dt><dd'+(o.fit?' data-fit-text':'')+'>'+esc(display)+'</dd></div>'}
 function tabela(rows,empty){var html=rows.filter(Boolean).join("");return html?'<dl class="bp-info-list">'+html+'</dl>':'<div class="bp-state">'+esc(empty||"Vir za ta sklop ni vrnil podatkov.")+'</div>'}
 function prilagodiBesedilo(scope){if(typeof window==="undefined"||!window.UJPrilagodiVelikostBesedila)return;(scope||document).querySelectorAll("[data-fit-text]").forEach(window.UJPrilagodiVelikostBesedila)}
 function zunanjiLink(url,label){try{var u=new URL(String(url||""));if(u.protocol!=="https:"&&u.protocol!=="http:")return "";return '<a class="bp-source-link" href="'+esc(u.href)+'" target="_blank" rel="noopener">'+esc(label||"Odpri vir")+' ↗</a>'}catch(e){return ""}}
 function oseba(x){x=x||{};var n=x.natural_person||x.person||{},ime=first(x.name,n.name,[n.first_name,n.last_name].filter(Boolean).join(" "),[x.first_name,x.last_name].filter(Boolean).join(" "));return {name:ime,role:first(x.role_detail&&x.role_detail.label_de,x.role_detail&&x.role_detail.label_en,x.role,x.position),city:first(n.city,x.city),start:first(x.start_date,x.since),end:first(x.end_date,x.until)}}
 function osebeHtml(items,title){if(!Array.isArray(items)||!items.length)return "";return '<section class="bp-subsection"><h4>'+esc(title)+'</h4><div class="bp-grid">'+items.slice(0,30).map(function(item){var p=oseba(item);return '<article class="bp-card"><h4>'+esc(p.name||"Neimenovana oseba")+'</h4>'+tabela([vrstica("Vloga",p.role),vrstica("Kraj",p.city),vrstica("Od",p.start,{date:true}),vrstica("Do",p.end,{date:true})],"Podrobnosti niso navedene.")+'</article>'}).join("")+'</div></section>'}
 function kratkiDatum(v){if(!present(v))return "";var d=new Date(v);return isNaN(d.getTime())?String(v):d.toLocaleDateString("sl-SI")}
 function delez(v){if(!present(v))return "";var n=Number(v);return isFinite(n)?new Intl.NumberFormat("sl-SI",{maximumFractionDigits:4}).format(n)+" %":String(v)}
 function nominalniDelez(v){if(!present(v))return "";var n=Number(v);return isFinite(n)?new Intl.NumberFormat("sl-SI",{maximumFractionDigits:2}).format(n)+" EUR":String(v)}
 function lastnik(x){x=x||{};var n=x.natural_person||{},l=x.legal_person||{},name=first(x.name,n.full_name,[n.first_name,n.last_name].filter(Boolean).join(" "),l.name);return {name:name,type:present(n.full_name)||present(n.first_name)?"Fizična oseba":present(l.name)?"Pravna oseba":"Lastnik",city:first(n.city,l.city,x.city),country:first(n.country,l.country,x.country),companyId:first(l.company_id,x.company_id),percentage:first(x.percentage_share,x.percentage,x.share_percentage),nominal:first(x.nominal_share,x.nominal),start:first(x.start,x.start_date),end:first(x.end,x.end_date)}}
 function lastnikiHtml(data,title){var x=data||{},items=first(x.owners,x.ubos,x.historical_owners,x.results);items=Array.isArray(items)?items:[];if(!items.length)return '<div class="bp-state">OpenRegister ni vrnil strukturiranih podatkov o lastnikih. To ne pomeni, da družba nima lastnikov; seznam družbenikov morda še ni obdelan ali ni na voljo v izbranem paketu.</div>';
  var note=x.best_available?'<p class="bp-note">Prikazani so najboljši trenutno razpoložljivi podatki. Pri nekaterih pravnih oblikah morda ne odražajo zadnje spremembe.</p>':"";
  var source=Array.isArray(x.sources)&&x.sources.length?zunanjiLink(x.sources[0].document_url||x.sources[0].url,"Odpri dokazni dokument"):"";
  return note+'<div class="bp-grid">'+items.slice(0,50).map(function(item){var o=lastnik(item);return '<article class="bp-card bp-owner-card"><span class="bp-badge">'+esc(o.type)+'</span><h4>'+esc(o.name||"Neimenovan lastnik")+'</h4>'+tabela([vrstica("Lastniški delež",delez(o.percentage)),vrstica("Nominalni delež",nominalniDelez(o.nominal)),vrstica("Kraj",[o.city,o.country].filter(Boolean).join(", ")),vrstica("Povezano podjetje",o.companyId),vrstica("Lastnik od",kratkiDatum(o.start)),vrstica("Lastnik do",kratkiDatum(o.end))],"Dodatne podrobnosti niso navedene.")+'</article>'}).join("")+'</div>'+(source?'<div class="bp-card-actions">'+source+'</div>':"")
 }
 function holdingsHtml(data){var x=data||{},items=Array.isArray(x.holdings)?x.holdings:Array.isArray(x.results)?x.results:[];if(!items.length)return '<div class="bp-state">Ni podatka, da bi bilo to podjetje lastnik deleža v drugem podjetju.</div>';return '<div class="bp-grid">'+items.slice(0,50).map(function(item){return '<article class="bp-card"><h4>'+esc(first(item.name,item.legal_name,"Neimenovano podjetje"))+'</h4>'+tabela([vrstica("OpenRegister ID",item.company_id),vrstica("Delež",delez(first(item.percentage_share,item.percentage))),vrstica("Nominalni delež",nominalniDelez(first(item.nominal_share,item.nominal))),vrstica("Od",kratkiDatum(first(item.start,item.start_date))),vrstica("Do",kratkiDatum(first(item.end,item.end_date)))],"Dodatne podrobnosti niso navedene.")+'</article>'}).join("")+'</div>'}
 var financneOznake={balance_sheet_total:"Bilančna vsota",revenue:"Prihodki",net_income:"Čisti poslovni izid",profit:"Dobiček",loss:"Izguba",cash:"Denarna sredstva",equity:"Kapital",liabilities:"Obveznosti",employees:"Število zaposlenih",fixed_assets:"Dolgoročna sredstva",current_assets:"Kratkoročna sredstva"};
 var financneMetrike=[{key:"net_income",label:"Dobiček"},{key:"balance_sheet_total",label:"Bilančna vsota"}];
 function financnoStevilo(value){if(!present(value))return null;var n=Number(value);return isFinite(n)?n:null}
 function letoKazalnika(row){var value=first(row&&row.date,row&&row.report_end_date,row&&row.report_date,row&&row.year),match=String(value||"").match(/(?:19|20)\d{2}/);return match?match[0]:""}
 function financniNiz(data,key){var indicators=data&&Array.isArray(data.indicators)?data.indicators:[],years={};indicators.forEach(function(row){var year=letoKazalnika(row),value=financnoStevilo(row&&row[key]);if(!year||value===null||years[year])return;years[year]={year:year,value:value,date:first(row.date,row.report_end_date,row.report_date,row.year)}});return Object.keys(years).sort().map(function(year){return years[year]}).slice(-8)}
 function lepaFinancnaMeja(value){var wanted=Math.max(1,Math.abs(Number(value)||0)*1.1),power=Math.pow(10,Math.floor(Math.log10(wanted))),normalized=wanted/power,steps=[1,1.2,1.5,2,2.5,3,4,5,6,8,10],step=steps.find(function(candidate){return candidate>=normalized})||10;return step*power}
 function financnaLestvica(series){var values=series.map(function(point){return point.value}),lowest=Math.min.apply(Math,[0].concat(values)),highest=Math.max.apply(Math,[0].concat(values)),hasNegative=lowest<0,limit=lepaFinancnaMeja(Math.max(Math.abs(lowest),Math.abs(highest)));return hasNegative?{min:-limit,max:limit,ticks:[limit,limit/2,0,-limit/2,-limit]}:{min:0,max:limit,ticks:[limit,limit*.75,limit*.5,limit*.25,0]}}
 function kratekDenar(value,currency){var n=Number(value),absolute=Math.abs(n),unit="",divisor=1;if(absolute>=1000000000){unit=" mrd.";divisor=1000000000}else if(absolute>=1000000){unit=" mio";divisor=1000000}else if(absolute>=1000){unit=" tis.";divisor=1000}var formatted=new Intl.NumberFormat("sl-SI",{maximumFractionDigits:absolute/divisor<10?1:0}).format(n/divisor),oznaka=(currency||"EUR")==="EUR"?"€":String(currency||"");return formatted+unit+(oznaka?" "+oznaka:"")}
 function financniGrafHtml(metric,series,currency,active){var scale=financnaLestvica(series),range=scale.max-scale.min,position=function(value){return Math.max(0,Math.min(100,(scale.max-value)/range*100))},zero=position(0),lines=scale.ticks.map(function(tick){var top=position(tick),zeroClass=Math.abs(tick)<1e-9?" bp-fin-chart__line--zero":"";return '<span class="bp-fin-chart__line'+zeroClass+'" style="top:'+top.toFixed(3)+'%"></span>'}).join(""),axis=scale.ticks.map(function(tick){return '<span style="top:'+position(tick).toFixed(3)+'%">'+esc(kratekDenar(tick,currency))+'</span>'}).join(""),bars=series.map(function(point){var valuePosition=position(point.value),top=Math.min(zero,valuePosition),height=Math.max(.8,Math.abs(zero-valuePosition)),tone=point.value<0?"negative":"positive",label=metric.label+" "+point.year+": "+denar(point.value,currency);return '<div class="bp-fin-chart__column"><span class="bp-fin-chart__bar bp-fin-chart__bar--'+tone+'" style="top:'+top.toFixed(3)+'%;height:'+height.toFixed(3)+'%" role="img" aria-label="'+esc(label)+'" title="'+esc(label)+'"></span></div>'}).join(""),years=series.map(function(point){return '<span>'+esc(point.year)+'</span>'}).join("");return '<div class="bp-key-chart" id="bp-fin-chart-'+esc(metric.key)+'" role="tabpanel" aria-labelledby="bp-fin-tab-'+esc(metric.key)+'" data-bp-fin-chart-panel="'+esc(metric.key)+'"'+(active?'':' hidden')+'><div class="bp-fin-chart__frame"><div class="bp-fin-chart__axis" aria-hidden="true">'+axis+'</div><div class="bp-fin-chart__plot" style="--bp-bar-count:'+series.length+'">'+lines+'<div class="bp-fin-chart__bars">'+bars+'</div></div></div><div class="bp-fin-chart__years" style="--bp-bar-count:'+series.length+'" aria-hidden="true">'+years+'</div></div>'}
 function financniGrafiHtml(data,currency){var available=financneMetrike.map(function(metric){return{metric:metric,series:financniNiz(data,metric.key)}}).filter(function(item){return item.series.length});if(!available.length)return "";var tabs=available.map(function(item,index){var active=index===0;return '<button type="button" id="bp-fin-tab-'+esc(item.metric.key)+'" role="tab" aria-controls="bp-fin-chart-'+esc(item.metric.key)+'" aria-selected="'+(active?'true':'false')+'" tabindex="'+(active?'0':'-1')+'" data-bp-fin-metric="'+esc(item.metric.key)+'" data-fit-text>'+esc(item.metric.label)+'</button>'}).join(""),charts=available.map(function(item,index){return financniGrafHtml(item.metric,item.series,currency,index===0)}).join("");return '<section class="bp-key-figures" aria-label="Ključni finančni kazalniki"><h4>Ključni kazalniki</h4><div class="bp-fin-metric-tabs" role="tablist" aria-label="Izberite finančni kazalnik">'+tabs+'</div>'+charts+'</section>'}
 function indikatorjiVrstice(data){var indicators=data&&Array.isArray(data.indicators)?data.indicators:[],latest=indicators[0]||{};return Object.keys(financneOznake).filter(function(key){return financnoStevilo(latest[key])!==null}).map(function(key){return{name:key,current_value:latest[key]}})}
 function veziFinancneGrafe(scope){if(!scope)return;var buttons=Array.from(scope.querySelectorAll("[data-bp-fin-metric]")),panels=Array.from(scope.querySelectorAll("[data-bp-fin-chart-panel]"));buttons.forEach(function(button){button.onclick=function(){var selected=button.getAttribute("data-bp-fin-metric");buttons.forEach(function(other){var active=other===button;other.setAttribute("aria-selected",active?"true":"false");other.tabIndex=active?0:-1});panels.forEach(function(panel){panel.hidden=panel.getAttribute("data-bp-fin-chart-panel")!==selected})}})}
 function financnaOznaka(row){var key=String(row&&row.name||"").toLowerCase();return first(row&&row.formatted_name,financneOznake[key],key.replace(/_/g," ").replace(/^./,function(c){return c.toUpperCase()}),"Finančna postavka")}
 function financneVrstice(rows,currency){if(!Array.isArray(rows))return "";return rows.slice(0,30).map(function(row){var values=row&&row.values&&typeof row.values==="object"?row.values:null,valueKeys=values?Object.keys(values).sort():[],latestValue=valueKeys.length?values[valueKeys[valueKeys.length-1]]:"",current=first(row&&row.current_value,latestValue),previous=row&&row.previous_value;return '<div class="bp-fin-row"><strong data-fit-text>'+esc(financnaOznaka(row))+'</strong><span data-fit-text>'+esc(denar(current,currency)||"Ni podatka")+'</span>'+(present(previous)?'<small>Prejšnje obdobje: '+esc(denar(previous,currency))+'</small>':"")+'</div>'}).join("")}
 function financialsHtml(data){var x=data||{},reports=Array.isArray(x.reports)?x.reports:[],indicators=Array.isArray(x.indicators)?x.indicators:[],latest=reports[0]||x.merged||{},latestIndicator=indicators[0]||{},currency=first(latest.currency,latestIndicator.currency,x.currency,"EUR"),period=first(latest.report_end_date,latest.report_date,latest.year,latestIndicator.date,latestIndicator.year),metricSource=first(latest.key_metrics,latest.metrics,x.key_metrics,x.metrics),indicatorRows=indikatorjiVrstice(x);if(!metricSource||(typeof metricSource==="object"&&!Array.isArray(metricSource)&&!Object.keys(metricSource).length))metricSource=indicatorRows;var sections=[["Ključni kazalniki",metricSource],["Aktiva",latest.aktiva&&latest.aktiva.rows],["Pasiva",latest.passiva&&latest.passiva.rows],["Izkaz poslovnega izida",latest.guv&&latest.guv.rows]],cards=sections.map(function(s){var rows=Array.isArray(s[1])?s[1]:s[1]&&typeof s[1]==="object"?Object.keys(s[1]).map(function(k){return{name:k,current_value:s[1][k]}}):[],body=financneVrstice(rows,currency);return body?'<section class="bp-subsection"><h4>'+esc(s[0])+'</h4><div class="bp-fin-list">'+body+'</div></section>':""}).join(""),charts=financniGrafiHtml(x,currency),content=charts+(cards?'<div class="bp-section-stack">'+cards+'</div>':"");return '<article class="bp-explain"><strong>Objavljeni finančni podatki</strong><span>Podatki izvirajo iz objav v Bundesanzeigerju in so lahko starejši od trenutnega poslovanja podjetja.</span></article>'+(period?'<p class="bp-note">Zadnje prikazano obdobje: '+esc(kratkiDatum(period))+'.</p>':"")+(content||'<div class="bp-state">OpenRegister ni vrnil strukturiranih finančnih podatkov. To ne pomeni, da podjetje nima prihodkov ali premoženja; za to pravno obliko oziroma obdobje objava morda ni na voljo.</div>')}
 var vrsteDokumentov={current_printout:"Trenutni registrski izpis",chronological_printout:"Kronološki izpis",historical_printout:"Zgodovinski izpis",shareholder_list:"Seznam družbenikov",articles_of_association:"Družbena pogodba",structured_information:"Strukturirani podatki"};
 function documentName(x){return vrsteDokumentov[String(x&&x.category||x&&x.type||"")]||first(x&&x.name,x&&x.file_name,x&&x.filename,"Registrski dokument")}
 function documentsHtml(data){var docs=data&&Array.isArray(data.documents)?data.documents:[],types=Object.keys(vrsteDokumentov);return '<article class="bp-explain"><strong>Dokumenti se pridobijo samo na vašo zahtevo.</strong><span>Vsaka pridobitev aktualnega dokumenta iz Handelsregister porabi 10 kreditov. Strukturirani podatki so lahko v obliki XML.</span></article><h4 class="bp-section-heading">Uradni dokumenti na zahtevo</h4><div class="bp-grid">'+types.map(function(type){return '<article class="bp-card"><h4 data-fit-text>'+esc(vrsteDokumentov[type])+'</h4><button class="bp-secondary" data-realtime-doc="'+type+'">Pridobi (10 kreditov)</button></article>'}).join("")+'</div>'+(docs.length?'<h4 class="bp-section-heading">Že navedeni dokumenti</h4><div class="bp-grid">'+docs.slice(0,100).map(function(x){var direct=first(x.document_url,x.url),id=first(x.id,x.document_id),date=first(x.file_date,x.date,x.created_at);return '<article class="bp-card"><span class="bp-badge">'+esc(String(x.category||x.type||"dokument").toUpperCase())+'</span><h4 data-fit-text>'+esc(documentName(x))+'</h4>'+tabela([vrstica("Datum dokumenta",date,{date:true}),vrstica("Ime datoteke",x.file_name,{fit:true})],"Dodatni podatki niso navedeni.")+(direct?'<a class="bp-secondary" target="_blank" rel="noopener" href="'+esc(direct)+'">Odpri dokument</a>':id?'<button class="bp-secondary" data-doc="'+esc(id)+'">Pridobi dokument (10 kreditov)</button>':'<p class="bp-note">Povezava za prenos ni na voljo.</p>')+'</article>'}).join("")+'</div>':'<div class="bp-state bp-state--compact">OpenRegister trenutno ni vrnil seznama že razpoložljivih dokumentov.</div>')}
 function uboHtml(data){var x=data||{},items=first(x.ubos,x.owners,x.beneficial_owners,x.results);items=Array.isArray(items)?items:[];if(!items.length)return '<div class="bp-state">OpenRegister ni vrnil strukturiranih podatkov o dejanskih lastnikih (UBO). To ne pomeni, da podjetje nima dejanskega lastnika; podatek morda ni dostopen v paketu ali še ni obdelan.</div>';return '<article class="bp-explain"><strong>Dejanski lastnik (UBO) ni nujno direktor ali neposredni družbenik.</strong><span>Spodaj so prikazane samo osebe, ki jih je vir vrnil kot dejanske lastnike.</span></article><div class="bp-grid">'+items.slice(0,50).map(function(item){var o=lastnik(item),reason=first(item.nature_of_control,item.control_type,item.reason),birth=first(item.date_of_birth,item.natural_person&&item.natural_person.date_of_birth);return '<article class="bp-card bp-owner-card"><span class="bp-badge">Dejanski lastnik</span><h4 data-fit-text>'+esc(o.name||"Neimenovana oseba")+'</h4>'+tabela([vrstica("Neposredni ali pripisani delež",delez(o.percentage)),vrstica("Način nadzora",reason),vrstica("Kraj",[o.city,o.country].filter(Boolean).join(", ")),vrstica("Datum rojstva",birth,{date:true}),vrstica("Velja od",o.start,{date:true})],"Dodatne podrobnosti niso navedene.")+'</article>'}).join("")+'</div>'}
 function historyHtml(data){var x=data||{},items=Array.isArray(x.owners)?x.owners:Array.isArray(x.historical_owners)?x.historical_owners:[];if(!items.length)return '<div class="bp-state">OpenRegister ni vrnil strukturirane zgodovine lastništva. To ne pomeni, da sprememb ni bilo; starejši seznami družbenikov morda še niso obdelani.</div>';return '<article class="bp-explain"><strong>Zgodovina temelji na vloženih seznamih družbenikov.</strong><span>Datum kaže pojav v dokumentu, ne nujno dan sklenitve posla.</span></article><div class="bp-section-stack">'+items.slice(0,50).map(function(item){var events=Array.isArray(item.ownership_history)?item.ownership_history:[];return '<section class="bp-subsection"><h4 data-fit-text>'+esc(first(item.name,"Neimenovan lastnik"))+'</h4>'+tabela([vrstica("Prvi pojav",item.first_appearance,{date:true}),vrstica("Zadnji pojav",item.last_appearance,{date:true}),vrstica("Država",item.country)],"Splošni podatki niso navedeni.")+(events.length?'<div class="bp-history">'+events.slice(0,100).map(function(event){return '<div><time>'+esc(kratkiDatum(event.document_date)||"Datum ni naveden")+'</time><strong>'+esc(delez(first(event.percentage_shares,event.percentage_share))||"Delež ni naveden")+'</strong><span>'+esc(nominalniDelez(first(event.nominal_shares,event.nominal_share))||"Nominalni delež ni naveden")+'</span></div>'}).join("")+'</div>':'<p class="bp-note">Posamezni zgodovinski dogodki niso navedeni.</p>')+'</section>'}).join("")+'</div>'}
 function transparencyHtml(data){var x=data||{},docs=first(x.documents,x.extracts,x.files);docs=Array.isArray(docs)?docs:[];var status=String(x.status||(docs.length||x.completed_at?"completed":"processing")).toLowerCase(),ready=["completed","ready","done","success"].includes(status)||docs.length>0,failed=["failed","error","rejected"].includes(status),report=x.report||{},ubos=Array.isArray(report.ubos)?report.ubos:[],tone=ready?"green":failed?"red":"yellow",title=ready?"Izpis Transparenzregister je pripravljen":failed?"Izpisa ni bilo mogoče pripraviti":"Izpis se še pripravlja",message=ready?"Spodaj so prikazane povezave do razpoložljivih uradnih dokumentov.":failed?"Preverite razlog in po potrebi poskusite znova.":"Obdelava pri viru še poteka. Ponovno preverjanje stanja ne porabi kreditov.";return '<article class="bp-result-card bp-result-card--'+tone+'"><span class="bp-badge bp-badge--'+tone+'">'+esc(slovenskiStatus(status))+'</span><h4>'+esc(title)+'</h4><p>'+esc(message)+'</p></article>'+tabela([vrstica("Referenčna številka",x.reference_number,{fit:true}),vrstica("Čas naročila",first(x.submitted_at,x.created_at,x.ordered_at),{date:true}),vrstica("Čas zaključka",first(x.completed_at,x.updated_at),{date:true}),vrstica("Vrsta obvestila",report.notice_type),vrstica("Razlog",first(x.message,x.reason,report.fictional_ubo_reason))],"Dodatne podrobnosti niso navedene.")+(ubos.length?'<h4 class="bp-section-heading">Dejanski lastniki v izpisu</h4>'+uboHtml({ubos:ubos.map(function(item){var person=item.natural_person||{},interest=item.interest||{};return{name:person.full_name,natural_person:person,percentage_share:interest.percentage,nature_of_control:first(interest.scope,interest.type)}})}):"")+(docs.length?'<div class="bp-grid bp-doc-links">'+docs.map(function(doc){var url=first(doc.url,doc.download_url,doc.document_url),label=documentName(doc);return '<article class="bp-card"><h4 data-fit-text>'+esc(label)+'</h4>'+(url?zunanjiLink(url,"Odpri uradni dokument"):'<p class="bp-note">Povezava še ni na voljo.</p>')+'</article>'}).join("")+'</div>':"")}
 function companyHtml(data){var x=data&&data.company||data||{},name=x.name||{},address=x.address||{},register=x.register||{},capital=x.capital||{},contact=x.contact||{},currentAddress=address;
  if(Array.isArray(x.addresses)&&x.addresses.length)currentAddress=x.addresses[x.addresses.length-1]||address;
  if(Array.isArray(x.registers)&&x.registers.length)register=x.registers[x.registers.length-1]||register;
  if(Array.isArray(x.capitals)&&x.capitals.length)capital=x.capitals[x.capitals.length-1]||capital;
  var legalName=first(typeof name==="string"?name:"",name.name,name.legal_name,x.legal_name,x.company_name),legalForm=first(name.legal_form,x.legal_form),purpose=first(x.purpose&&x.purpose.purpose,x.purpose,Array.isArray(x.purposes)&&x.purposes.length&&x.purposes[x.purposes.length-1].purpose),addressValue=first(currentAddress.formatted_value,currentAddress.formatted,address.formatted_value,[currentAddress.street,currentAddress.postal_code,currentAddress.city].filter(Boolean).join(", "));
  var main='<section class="bp-subsection"><h4>Osnovni podatki</h4>'+tabela([vrstica("Pravno ime",legalName,{fit:true}),vrstica("Status",x.status,{status:true}),vrstica("Pravna oblika",String(legalForm||"").toUpperCase()),vrstica("Datum ustanovitve",first(x.incorporated_at,name.start_date),{date:true}),vrstica("Osnovni kapital",denar(capital.amount,capital.currency)),vrstica("Dejavnost",purpose)],"Osnovnih podatkov ni bilo mogoče prikazati.")+'</section>';
  var location='<section class="bp-subsection"><h4>Sedež in register</h4>'+tabela([vrstica("Uradni naslov",addressValue,{fit:true}),vrstica("Registrsko sodišče",first(register.register_court,x.register_court)),vrstica("Register",[first(register.register_type,x.register_type),first(register.register_number,x.register_number)].filter(Boolean).join(" ")),vrstica("OpenRegister ID",first(x.id,register.company_id,profile&&profile.company_id))],"Registrski podatki niso navedeni.")+'</section>';
  var contacts='<section class="bp-subsection"><h4>Kontakt</h4>'+tabela([vrstica("E-pošta",contact.email),vrstica("Telefon",contact.phone),vrstica("Davčna številka",first(contact.vat_id,x.vat_id)),vrstica("Spletna stran",contact.website_url)],"Kontaktni podatki niso navedeni.")+'</section>';
  return '<div class="bp-section-stack">'+main+location+contacts+osebeHtml(x.representation,"Zastopanje")+'</div>'
 }
 function insolvencyHtml(data){var x=data||{},official=x.officialVerification||x.official_verification||{},matches=Array.isArray(x.matches)?x.matches:[],clear=x.status==="clear",possible=x.status==="possible_match"||matches.length>0,unavailable=x.status==="unavailable";
  var tone=possible?"red":clear?"green":"yellow",title=possible?"Najden je možen insolvenčni zadetek":clear?"Za preverjene podatke ni najdene objave":unavailable?"Insolvenčnega vira ni bilo mogoče preveriti":"Preverjanje ni dokončano",message=possible?"Pred sodelovanjem ročno primerjajte dolžnika, kraj, register in opravilno številko.":clear?"To pomeni samo, da za preverjeno ime in lokacijo ob času poizvedbe ni bilo najdene objave; ni popolna bonitetna garancija.":"Rezultata ni mogoče razlagati kot potrditev plačilne sposobnosti.";
  var searched=tabela([vrstica("Iskano ime",first(x.searchedName,official.searchedName)),vrstica("Kraj",first(x.searchedCity,official.searchedCity)),vrstica("Poštna številka",x.searchedPostalCode),vrstica("Register",first(official.searchedRegister,x.searchedCompanyId)),vrstica("Čas preverbe",first(official.checkedAt,x.checkedAt),{date:true})],"Iskalni podatki niso shranjeni.");
  var result='<article class="bp-result-card bp-result-card--'+tone+'"><span class="bp-badge bp-badge--'+tone+'">'+esc(clear?"Brez objave":possible?"Ročni pregled":"Ni potrjeno")+'</span><h4>'+esc(title)+'</h4><p>'+esc(message)+'</p></article>';
  var hits=matches.length?'<section class="bp-subsection"><h4>Možni zadetki</h4><div class="bp-grid">'+matches.slice(0,5).map(function(m){return '<article class="bp-card"><h4>'+esc(first(m.debtor_name,m.name,"Neimenovan dolžnik"))+'</h4>'+tabela([vrstica("Postopek",first(m.case_number,m.file_number)),vrstica("Sodišče",m.court),vrstica("Status",m.current_status,{status:true})],"Podrobnosti niso navedene.")+'</article>'}).join("")+'</div></section>':"";
  var sourceUrl=first(official.sourceUrl,x.sourceUrl,x.apiSourceUrl),source='<section class="bp-subsection"><h4>Vir preverbe</h4>'+tabela([vrstica("Vir",first(official.sourceLabel,x.sourceLabel,"Insolvenzbekanntmachungen")),vrstica("Rezultat uradnega portala",official.reason==="no_publication_found"?"Ni najdene objave":slovenskiStatus(official.status)),vrstica("Število objav",present(official.publicationCount)?official.publicationCount:matches.length)],"Vir ni naveden.")+'<div class="bp-card-actions">'+zunanjiLink(sourceUrl,"Odpri uradni vir")+'</div></section>';
  return '<div class="bp-section-stack">'+result+'<section class="bp-subsection"><h4>Preverjeni iskalni podatki</h4>'+searched+'</section>'+hits+source+'</div>'
 }
 var skritiKljuci={apievidence:1,request:1,response:1,filters:1,pagination:1,sources:1,sourceurl:1,apisourceurl:1,endpoint:1,document_url:1,download_url:1,file_url:1};
 var prijazneOznake={status:"Status",name:"Ime",legal_name:"Pravno ime",role:"Vloga",city:"Kraj",postal_code:"Poštna številka",street:"Ulica",register_number:"Registrska številka",register_court:"Registrsko sodišče",register_type:"Vrsta registra",share:"Delež",percentage:"Delež",amount:"Znesek",currency:"Valuta",year:"Leto",revenue:"Prihodki",profit:"Dobiček",loss:"Izguba",assets:"Sredstva",liabilities:"Obveznosti",date:"Datum",start_date:"Velja od",end_date:"Velja do"};
 function safeFlatten(data,prefix,out,depth){out=out||[];depth=depth||0;if(!data||typeof data!=="object"||depth>3)return out;Object.keys(data).slice(0,50).forEach(function(k){var key=k.toLowerCase();if(skritiKljuci[key]||out.length>=35)return;var v=data[k],label=prijazneOznake[key]||k.replace(/_/g," ");if(v&&typeof v==="object"&&!Array.isArray(v)){safeFlatten(v,prefix?prefix+" – "+label:label,out,depth+1)}else if(Array.isArray(v)){if(v.length&&typeof v[0]!=="object")out.push([prefix?prefix+" – "+label:label,v.join(", ")]);else if(v.length)out.push([prefix?prefix+" – "+label:label,v.length+" zapisov"])}else if(present(v))out.push([prefix?prefix+" – "+label:label,typeof v==="boolean"?(v?"Da":"Ne"):v])});return out}
 function dataHtml(data){var rows=safeFlatten(data);return tabela(rows.map(function(r){return vrstica(r[0],r[1])}),"Vir za ta sklop ni vrnil uporabnih podatkov.")}
 function status(){var c=profile.latest_check||{},r=c.result||{},level=r.level||"yellow",map={green:"Brez zaznanega zadetka",red:"Potreben ročni pregled",yellow:"Delno potrjeno"};el("bp-level").className="bp-badge bp-badge--"+level;el("bp-level").textContent=map[level]||"Preverjeno";return r}
 function overview(){var r=status(),c=profile.latest_check||{};el("bp-section-content").innerHTML='<article class="bp-card"><h4>'+esc(r.title||"Shranjena preverba")+'</h4><p>'+esc(r.message||"Odprite posamezen zavihek za aktualne registrske podatke.")+'</p><p>Preverjeno: '+esc(new Date(profile.checked_at).toLocaleString("sl-SI"))+'</p></article>'+(c.insolvency?'<h4 class="bp-section-heading">Zadnja insolvenčna preverba</h4>'+insolvencyHtml(c.insolvency):"")}
 async function section(name,refresh,realtime){el("bp-section-state").hidden=false;el("bp-section-state").textContent="Pridobivam podatke …";el("bp-section-content").innerHTML="";try{var d=await api("/api/openregister-pro?action=section&profileId="+encodeURIComponent(profileId)+"&section="+encodeURIComponent(name)+(refresh?"&refresh=1":"")+(realtime?"&realtime=1":""));loaded[name]=d;el("bp-section-state").hidden=true;renderSection(name,d)}catch(e){el("bp-section-state").hidden=false;el("bp-section-state").textContent=e.code==="OPENREGISTER_PRO_NOT_CONFIGURED"?"OpenRegister Pro še ni povezan. Struktura je pripravljena in bo začela delovati po vnosu Pro API-ključa.":e.message}}
 function cacheNote(d){var c=d.cache||{},message=c.sourceMode==="processing"?"OpenRegister podatke še obdeluje; kreditov še ni porabil.":c.hit?'Uporabljen svež predpomnilnik; 0 novih kreditov.':'Pridobljeno iz OpenRegister; porabljeno '+(c.creditsUsed||0)+' kreditov.';return '<p class="bp-note">'+message+(c.fetchedAt?' Čas: '+esc(new Date(c.fetchedAt).toLocaleString("sl-SI"))+'.':'')+'</p>'}
 function renderSection(name,d){var html="";if(name==="company")html='<div class="bp-card-actions"><button id="bp-realtime" class="bp-secondary">Osveži neposredno iz registra (+10 kreditov)</button></div>'+cacheNote(d)+companyHtml(d.data);else if(name==="insolvency")html=cacheNote(d)+insolvencyHtml(d.data);else if(name==="financials")html=cacheNote(d)+financialsHtml(d.data);else if(name==="documents")html=cacheNote(d)+documentsHtml(d.data);else html=cacheNote(d)+dataHtml(d.data);el("bp-section-content").innerHTML=html;prilagodiBesedilo(el("bp-section-content"));if(name==="financials")veziFinancneGrafe(el("bp-section-content"));if(name==="company"&&el("bp-realtime"))el("bp-realtime").onclick=function(){if(confirm("Neposredna osvežitev porabi dodatnih 10 kreditov. Nadaljujem?"))section("company",true,true)};if(name==="documents"){document.querySelectorAll("[data-doc]").forEach(function(b){b.onclick=function(){loadDocument(b.dataset.doc,b)}});document.querySelectorAll("[data-realtime-doc]").forEach(function(b){b.onclick=function(){loadRealtimeDocument(b.dataset.realtimeDoc,b)}})}}
 async function loadDocument(id,b){if(!id)return;var old=b.textContent;b.disabled=true;b.textContent="Pridobivam …";try{var d=await api("/api/openregister-pro",{method:"POST",body:JSON.stringify({action:"document",profileId:profileId,documentId:id})});var doc=d.document||{},url=doc.url||doc.download_url||doc.file_url;if(url){window.open(url,"_blank","noopener")}else{var state=document.createElement("p");state.className="bp-error";state.textContent="OpenRegister ni vrnil povezave do dokumenta. Tehnični odgovor je zaradi varnosti skrit.";b.closest("article").appendChild(state)}}catch(e){fail(e)}finally{b.disabled=false;b.textContent=old}}
 async function loadRealtimeDocument(category,b){if(!confirm("Pridobitev tega uradnega dokumenta porabi 10 kreditov. Nadaljujem?"))return;var old=b.textContent;b.disabled=true;b.textContent="Pridobivam …";try{var d=await api("/api/openregister-pro",{method:"POST",body:JSON.stringify({action:"document_realtime",profileId:profileId,category:category})}),doc=d.document||{};if(doc.url)window.open(doc.url,"_blank","noopener");else throw new Error("OpenRegister ni vrnil povezave do dokumenta.")}catch(e){fail(e)}finally{b.disabled=false;b.textContent=old}}
 async function ownership(){el("bp-section-state").hidden=false;el("bp-section-state").textContent="Pridobivam lastništvo in deleže …";var results=await Promise.allSettled([api("/api/openregister-pro?action=section&profileId="+encodeURIComponent(profileId)+"&section=owners"),api("/api/openregister-pro?action=section&profileId="+encodeURIComponent(profileId)+"&section=holdings")]),owners=results[0],holdings=results[1],ownersHtml=owners.status==="fulfilled"?cacheNote(owners.value)+lastnikiHtml(owners.value.data,"Lastniki"):'<p class="bp-error">Lastnikov ni bilo mogoče pridobiti: '+esc(owners.reason&&owners.reason.message||"vir ni dosegljiv")+'</p>',holdingsSection=holdings.status==="fulfilled"?cacheNote(holdings.value)+holdingsHtml(holdings.value.data):'<p class="bp-error">Deležev v drugih podjetjih ni bilo mogoče pridobiti: '+esc(holdings.reason&&holdings.reason.message||"vir ni dosegljiv")+'</p>';el("bp-section-state").hidden=true;el("bp-section-content").innerHTML='<article class="bp-explain"><strong>Direktor oziroma zastopnik ni nujno lastnik.</strong><span>Vodstvo je prikazano v zavihku Podjetje. Spodaj so ločeno prikazani družbeniki tega podjetja in podjetja, v katerih ima preverjeno podjetje delež.</span></article><h4 class="bp-section-heading">Družbeniki oziroma lastniki</h4>'+ownersHtml+'<h4 class="bp-section-heading">Deleži tega podjetja v drugih družbah</h4>'+holdingsSection+'<div class="bp-card-actions"><button id="bp-ubo" class="bp-secondary">Pridobi dejanske lastnike (25 kreditov)</button><button id="bp-history" class="bp-secondary">Pridobi zgodovino lastništva (25 kreditov)</button><button id="bp-transparency" class="bp-secondary">Naroči izpis Transparenzregister (25 kreditov)</button></div><div id="bp-extra"></div>';el("bp-ubo").onclick=function(){extra("ubo")};el("bp-history").onclick=function(){extra("historical_owners")};el("bp-transparency").onclick=transparency}
 async function transparency(){if(!confirm("Naročilo uradnega izpisa Transparenzregister porabi 25 kreditov in zahteva predhodno shranjene poverilnice v OpenRegister. Nadaljujem?"))return;var box=el("bp-extra");box.innerHTML='<div class="bp-state">Naročam izpis …</div>';try{var d=await api("/api/openregister-pro",{method:"POST",body:JSON.stringify({action:"transparency_order",profileId:profileId})}),x=d.extract||{};box.innerHTML='<h4 class="bp-section-heading">Transparenzregister</h4>'+transparencyHtml(x)+'<div class="bp-card-actions"><button id="bp-poll-extract" class="bp-secondary">Preveri stanje (0 kreditov)</button></div>';prilagodiBesedilo(box);if(x.id)el("bp-poll-extract").onclick=function(){pollExtract(x.id)}}catch(e){box.innerHTML='<p class="bp-error">'+esc(e.message)+'</p>'}}
 async function pollExtract(id){var box=el("bp-extra");try{var d=await api("/api/openregister-pro",{method:"POST",body:JSON.stringify({action:"transparency_get",profileId:profileId,extractId:id})}),x=d.extract||{},state=String(x.status||"").toLowerCase(),processing=!x.completed_at&&!(Array.isArray(x.documents)&&x.documents.length)&&!["failed","error","rejected"].includes(state);box.innerHTML='<h4 class="bp-section-heading">Transparenzregister</h4>'+transparencyHtml(x)+(processing?'<div class="bp-card-actions"><button id="bp-poll-extract" class="bp-secondary">Ponovno preveri stanje</button></div>':'');prilagodiBesedilo(box);if(processing)el("bp-poll-extract").onclick=function(){pollExtract(id)}}catch(e){box.innerHTML='<p class="bp-error">'+esc(e.message)+'</p>'}}
 async function extra(name){var box=el("bp-extra");box.innerHTML='<div class="bp-state">Pridobivam …</div>';try{var d=await api("/api/openregister-pro?action=section&profileId="+encodeURIComponent(profileId)+"&section="+name),title=name==="ubo"?"Dejanski lastniki":"Zgodovina lastništva",content=name==="ubo"?uboHtml(d.data):historyHtml(d.data);box.innerHTML='<h4 class="bp-section-heading">'+title+'</h4>'+cacheNote(d)+content;prilagodiBesedilo(box)}catch(e){box.innerHTML='<p class="bp-error">'+esc(e.message)+'</p>'}}
 async function monitoring(){el("bp-section-state").hidden=true;var today=new Date().toISOString().slice(0,10),later=new Date(Date.now()+180*86400000).toISOString().slice(0,10);el("bp-section-content").innerHTML='<article class="bp-explain"><strong>Samodejna ponovna preverba za daljše projekte</strong><span>Vnesite vrednost in trajanje projekta. Sistem sam določi razmik preverjanj, zadnjo preverbo pa opravi tik pred zaključkom. Ročne poizvedbe imajo vedno prednost.</span></article><div class="bp-card bp-project-monitor"><h4>Projektno spremljanje</h4><div class="bp-form"><label>Vrednost projekta (€)<input id="bp-project-value" type="number" min="0" step="100" placeholder="npr. 25000"></label><label>Začetek<input id="bp-project-start" type="date" value="'+today+'"></label><label>Predviden konec<input id="bp-project-end" type="date" value="'+later+'"></label><div class="bp-form-actions"><button id="bp-project-on" class="bp-primary">Vključi spremljanje</button><button id="bp-project-off" class="bp-secondary">Izključi</button></div></div><p id="bp-project-status" class="bp-note">Samodejno spremljanje je trenutno na voljo za projekte od 10.000 € naprej.</p></div>';el("bp-project-on").onclick=function(){projectMonitor("project_monitor_save")};el("bp-project-off").onclick=function(){projectMonitor("project_monitor_delete")};try{var d=await api("/api/openregister-pro?action=project_monitor_get&profileId="+encodeURIComponent(profileId)),m=d.monitor;if(m){el("bp-project-value").value=(Number(m.project_value_cents)/100).toFixed(0);el("bp-project-start").value=m.project_start_date;el("bp-project-end").value=m.project_end_date;el("bp-project-status").textContent=m.completed_at?"Projekt je zaključen. Zadnja preverba: "+new Date(m.last_check_at).toLocaleString("sl-SI"):"Vključeno: preverba na "+m.interval_days+" dni. Naslednja: "+new Date(m.next_check_at).toLocaleString("sl-SI")+(m.last_result_status?" · Zadnji rezultat: "+m.last_result_status:"")}}catch(e){el("bp-project-status").textContent=e.message}}
 async function projectMonitor(action){var s=el("bp-project-status");s.textContent="Shranjujem …";try{var d=await api("/api/openregister-pro",{method:"POST",body:JSON.stringify({action:action,profileId:profileId,projectValue:Number(el("bp-project-value").value),startDate:el("bp-project-start").value,endDate:el("bp-project-end").value})});if(action==="project_monitor_delete")s.textContent="Projektno spremljanje je izključeno.";else{s.textContent="Spremljanje je vključeno. Preverba bo izvedena na "+d.monitor.interval_days+" dni; naslednja "+new Date(d.monitor.next_check_at).toLocaleString("sl-SI")+"."}}catch(e){s.textContent=e.message}}
 function choose(name){document.querySelectorAll(".bp-tabs button").forEach(function(b){b.classList.toggle("is-active",b.dataset.tab===name)});el("bp-section-title").querySelector("h3").textContent=config[name].title;el("bp-section-credit").textContent=config[name].cost;el("bp-section-state").hidden=true;el("bp-section-content").innerHTML="";history.replaceState(null,"",location.pathname+location.search+(name==="overview"?"":"#"+name));if(name==="overview")overview();else if(name==="ownership")ownership();else if(name==="monitoring")monitoring();else section(name)}
 async function init(){if(!/^[0-9a-f-]{36}$/i.test(profileId)){fail(new Error("Profil ni veljaven."));return}try{var d=await api("/api/boniteta-profili?id="+encodeURIComponent(profileId));profile=d.profile;var a=profile.address||{};el("bp-name").textContent=profile.legal_name;el("bp-subtitle").textContent=[profile.register_number,profile.register_court].filter(Boolean).join(" · ")||"Podatki uporabniško potrjene identitete";el("bp-recheck").href="bonitetna-preverba.html?ime="+encodeURIComponent(profile.legal_name);el("bp-summary").innerHTML=[["Status",slovenskiStatus(profile.company_status||"Ni podatka")],["Naslov",[a.street||a.address,a.postal_code||a.postalCode,a.city].filter(Boolean).join(", ")||"Ni podatka"],["Zadnja preverba",new Date(profile.checked_at).toLocaleString("sl-SI")],["OpenRegister ID",profile.company_id||"Ni uradno povezano"]].map(function(x){return '<div><dt>'+esc(x[0])+'</dt><dd data-fit-text>'+esc(x[1])+'</dd></div>'}).join("");el("bp-profile-loading").hidden=true;el("bp-profile").hidden=false;if(window.UJPrilagodiVelikostBesedila)document.querySelectorAll("[data-fit-text]").forEach(window.UJPrilagodiVelikostBesedila);document.querySelectorAll(".bp-tabs button").forEach(function(b){b.onclick=function(){choose(b.dataset.tab)}});choose(config[location.hash.slice(1)]?location.hash.slice(1):"overview")}catch(e){el("bp-profile-loading").hidden=true;fail(e)}}
 if(typeof module==="object"&&module.exports){module.exports={companyHtml:companyHtml,insolvencyHtml:insolvencyHtml,lastnikiHtml:lastnikiHtml,holdingsHtml:holdingsHtml,financialsHtml:financialsHtml,financniNiz:financniNiz,financniGrafiHtml:financniGrafiHtml,documentsHtml:documentsHtml,uboHtml:uboHtml,historyHtml:historyHtml,transparencyHtml:transparencyHtml,safeFlatten:safeFlatten};return}init();
})();
